name: Swift
on: [push]
jobs:

  macos:
    name: macOS
    runs-on: macos-15
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Swift Version
      run: swift --version
    - name: Build (Debug)
      run: swift build -c debug
    - name: Build (Release)
      run: swift build -c release
    - name: Test (Debug)
      run: swift test -c debug
  
  linux-x86:
    name: Linux
    strategy:
      matrix:
        container: ["swift:6.0.3", "swift:6.1.1", "swiftlang/swift:nightly"]
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}-jammy
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Swift Version
      run: swift --version
    - name: Build (Debug)
      run: swift build -c debug --build-tests
    - name: Build (Release)
      run: swift build -c release

  linux-armv7:
      name: Armv7 Debian Bookworm
      runs-on: ubuntu-latest
      container: swift:6.0.3
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Install dependencies
          run: apt update -y; apt install wget -y
        - name: Install SDK
          run: |
            wget https://github.com/xtremekforever/swift-armv7/releases/download/6.0.3/swift-6.0.3-RELEASE-debian-bookworm-armv7-sdk.tar.gz
            tar -xvf swift-6.0.3-RELEASE-debian-bookworm-armv7-sdk.tar.gz
            mv swift-6.0.3-RELEASE-debian-bookworm-armv7 /opt/swift-6.0.3-RELEASE-debian-bookworm-armv7
        - name: Swift Version
          run: swift --version
        - name: Build
          run: swift build --build-tests --destination /opt/swift-6.0.3-RELEASE-debian-bookworm-armv7/debian-bookworm.json
        - name: Upload artifacts
          uses: actions/upload-artifact@v4
          with:
            name: "armv7-bookworm"
            path: .build/armv7-unknown-linux-gnueabihf/debug/BinderPackageTests.xctest

  android:
    name: Android
    strategy:
      fail-fast: false
      matrix:
        swift: ['6.1', 'nightly-6.2']
    runs-on: macos-15
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: "Build Swift Package for Android"
        run: |
          brew install skiptools/skip/skip || (brew update && brew install skiptools/skip/skip)
          skip android sdk install --version ${{ matrix.swift }}
          # https://github.com/swiftlang/swift-driver/pull/1879
          ANDROID_NDK_ROOT="" skip android build